---
plugins-to-download:
  plugins:
  - name: custom-post-type-ui
  - name: custom-post-type-permalinks
  - name: post-types-order
  - name: disable-comments
  - name: updraftplus
  - name: file-manager-advanced
  - name: relevanssi
  - name: acf-youtube-picker
  - name: force-regenerate-thumbnails
  - name: wp-ses
  - name: safe-svg
  - name: wp-external-links
  - name: disable-emojis
  - name: disable-embeds
  - name: wordpress-seo
  - name: mailchimp
  - name: ga-google-analytics
  - name: contact-form-7

plugins-to-copy:
  directory: dependencies/plugins
  plugins:
  - name: advanced-custom-fields-pro
    type: zip
    filename: advanced-custom-fields-pro.zip
  - name: two-factor-authentication-premium
    type: zip
    filename: two-factor-authentication-premium.zip
