---
plugins-to-download:
  plugins:
  - name: custom-post-type-ui
  - name: custom-post-type-permalinks
  - name: post-types-order
  - name: disable-comments
  - name: wp-db-backup
  - name: file-manager-advanced
  - name: relevanssi
  - name: acf-youtube-picker
  - name: force-regenerate-thumbnails
  - name: wp-ses
  - name: safe-svg

plugins-to-copy:
  directory: dependencies/plugins
  plugins:
  - name: advanced-custom-fields-pro
    type: zip
    filename: advanced-custom-fields-pro.5.7.3.zip
  - name: two-factor-authentication-premium
    type: zip
    filename: two-factor-authentication-premium.1.3.3.zip
